services:
  - type: web
    name: quickshop
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn QuickShop.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 4"
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: RENDER
        value: true
      - key: DJANGO_SETTINGS_MODULE
        value: QuickShop.settings
    disk:
      name: sqlite
      mountPath: /data
      sizeGB: 1 