services:
  - type: web
    name: quickshop
    env: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn QuickShop.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --log-level debug"
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: RENDER
        value: true
      - key: DJANGO_SETTINGS_MODULE
        value: QuickShop.settings
      - key: PYTHONPATH
        value: $RENDER_PROJECT_DIR
      - key: WSGI_APP
        value: QuickShop.wsgi:application
      - key: STATIC_ROOT
        value: $RENDER_PROJECT_DIR/staticfiles
      - key: MEDIA_ROOT
        value: $RENDER_PROJECT_DIR/media
      - key: PROJECT_DIR
        value: $RENDER_PROJECT_DIR
    disk:
      name: sqlite
      mountPath: /data
      sizeGB: 1 